### ISSUE TITLE
Save project settings in home/Robotbuilder

### ISSUE THREAD

**Issue by SamCarlberg** [wpilibsuite/RobotBuilder#34]
This would allow teams to have their RobotBuilder project files to be used by multiple people and let it be in their version control system.

Something like

```
~
|_ Robotbuilder
  |_ settings
    |_ gearsbot.yml
    |_ 2017bot.yml
    |_ practicebot.yml
    |_ ...
```

With the settings YAML files storing workspace, wiring file, etc.

```yaml
workspace: /home/sam/workspace
simulation_world_file: ...
wiring_file_location: ...
```
