### ISSUE TITLE
Discussion: Extensions vs Hardcoded for WPI components. 

### ISSUE THREAD

**Issue by cpapplefamily** [wpilibsuite/RobotBuilder#508]
I was panning through the 2023 changes through the Beta links and the PS4Controller class jumped out at me. Since this is a WPILib class I though about adding it to Robotbuilder like the Xbox Controller. I already created a working Extension and thought would it be possible to include an Extensions folder in the repository to easily add new components as needed vs editing the individual files that make RobotBuilder operate. 

Maybe there are other reasons to keep all of the WPILib components coded to the few internal files that I'm not aware of. If that is the case I can move my edits into the necessary files and create a Pull Request.

**Comment by cpapplefamily** [comment]
I believe I may have found that limitation. Seems that an extension does not "Currently" have knowledge of the macros with in the PalletteDescription.yanl file #Button("") 

```
!Component
  name: PS4 Button
  type: PS4 Button
  help: An PS4 Controller button that binds a driver action to a command.
  properties:
    - !ParentProperty
      name: Joystick
    - !ChoicesProperty
      name: Button
      choices: ["Circle","Cross","L1","L2","L3","Options","PS","R1","R2","R3","Share","Square","Touchpad","Triangle"]
      default: "Circle"
    #Button("")            <---------------- This Here
    - !BooleanProperty
      name: Send to SmartDashboard
      default: false
```

I suppose the Extension could recreate the required code but that violates -DRY-
